#!/bin/bash

docker build -t casparcg/base:1.3.0 tools/linux/base
docker build -t casparcg/cef:3.3239.1723-3 tools/linux/cef
docker build -t casparcg/boost:1.66-3 tools/linux/boost
docker build -t casparcg/ffmpeg:master-acdea9e-3 tools/linux/ffmpeg
docker build -t casparcg/qt:5.10.1 tools/linux/qt
